### ISSUE TITLE
Investigate and optimize Notion Database rows Retrieval

### ISSUE THREAD

**Issue by spolu** [dust-tt/dust#1202]

**Comment by spolu** [comment]
Try to understand the issue, find actual examples, try to introspect what we show the model, fix anything if needed otherwise arm user facing teams with an explanation :+1:

**Comment by fontanierh** [comment]
Got it thanks

**Comment by fontanierh** [comment]
Currently, notion databases (and tables) are indexed and queried the same way as the rest of our content, i.e as unstructured data.

As an example, here is how we would embed a table about animals:

```
Animals
||type|age|name|favourite food||
||cat|5|Chawarma|chicken||
||dog|11|Babine|fish||
||cat|3|Soupinou|croquettes||
```

Because of this, it is hard for Dust to provide answers about tables/databases as a whole because the model's prompt may contain only a subset of the rows (without any metadata about the table), and the model doesn't have the ability to query the structured data.

We'll likely work on adding support for structured data sources in the future.

**Comment by spolu** [comment]
Indeed an important point is that a chunk containing the data of interest might not include the table title which makes retrieval hard for some queries.

**Comment by spolu** [comment]
cc @gabhubert @Yutcam
