### ISSUE TITLE
improve "last synced" for non-webhook managed datasources for clarity

### ISSUE THREAD

**Issue by spolu** [dust-tt/dust#1421]

**Comment by gabhubert** [comment]
Unclear how much we can improve it given the garbage collection constraint, but now it's sort of downright misleading between the data source synce timestamp and doc sync timestamp. I think we're conflating 2 things: 
- when we last worked on a thing
- when we last considered a data source "OK"

@Duncid this might need some more thinking, because basically I think we're bad at showing an "orange" status (we're progressing but have some skipped DBs, eg)

**Comment by Duncid** [comment]
I'm rethinking the activate / manage data source screens.
Let's have the discussion there.

**Comment by gabhubert** [comment]
sg—let's close this for now then
