### ISSUE TITLE
Agent suggestion for messages with no agent mention

### ISSUE THREAD

**Issue by spolu** [dust-tt/dust#1565]

**Comment by spolu** [comment]
Context and design here: https://dust4ai.slack.com/archives/C050A0S2Z7F/p1695131873350469

**Comment by spolu** [comment]
@philipperolet thanks for picking up!

I think we want to do the following:

rely on editUserMessage
in editUserMessage trigger an agent run if there was no AgentMessage after that UserMessage.

WDYT?

**Comment by philipperolet** [comment]
We could do that, I would be fine with it ; it's the simplest & fastest

Another option is to have editMessage handle mentions => re-run all mentions (expected behaviour if the user changes its message with a mention), as a new version for existing children messages from the mentions, and as fully new messages for new mentions

Intermediate solution: only run new mentions (as initially suggested by the function editMessage's comments) => as a follow-up feature, provide a retry icon on agentmessages whose parent has been edited

After thought, I'd go for that: editMessage creates new agentMessages for new mentions (and ignores old ones)

Back to you WDYT ? :)

**Comment by philipperolet** [comment]
Other topic: no mention always implies agent suggestion buttons?

I'm starting on this assumption since for a first iteration it feels ok, but might need discussion

**Comment by spolu** [comment]
On behavior of edit, agreed with your analysis. Let's start simple and complexify as need arise?

On suggestion:

Yes let's start with no mention implies suggestions. We'll see if this is too much or not.
We do want to have any bot in the conversation as first proposal.
