### ISSUE TITLE
[Caloris] Improve Chunking: Framing

### ISSUE THREAD

**Issue by spolu** [dust-tt/dust#2327]
Change data source API to receive pre-chunked parts of documents
Have connectors create better chunks (title repeated as an example)
Allow ventilation for chunk size to better split (bump to max 512? and cut at passed chunk boundary? eqiulibrate chunks within passed parts)

**Comment by spolu** [comment]
Probably need framing into sub-issues

**Comment by spolu** [comment]
The goal of the project is to improve retrieval quality by fixing some aspects that we can formally (not empirically) identify as low-hanging fruit improvement. Which means we won't seek to measure success empirically for this one.

## What we want to do for which we have very high confidence it will improve the state of things

- We want to increase chunk size. Model context sizes have more than double since we picked the 256 tokens and there's likely some value in increasing chunk size a bit to improve retrieval (less noisy) and improve generation (more context).
- We want to repeat minimal document structure in each chunk and repeat basic metadata about the document (title, if possible sections / sub-sections with indication that content was omitted, meta data about the document such as author and last update time)
- We want to allow for more flexibility in the chunking strategy to get more balanced chunks as well as chunks that better follow the overall document structure.

## What changed

- Model context sizes improved
- We have more experience
- We have access to cheap tokenization internally

## Today

Today we generally add some content metadata at the top of the document and chunk blindly at the 256 tokens boundary

## Proposed approach

### Change the API to help guide tokenization

Go from `text: string` (https://docs.dust.tt/documents#create-a-document) to the following:
```
{
  document: {
    prefix: string;
  };
  sections: {
    prefix:  string;
    content: string;
  };
} : DocumentContentType
```

The idea is to be able to encode the structure of the document to the chunk strategy.
The chunk stragegy will based on that:
- repeat `document.prefix` at the top of each chunk
- repeat `sections.prefix` at the top of each chunk emitted from this section
- for each section, balanced chunking strategy with a best-effort to split on newlines.

### API

We'll document this new API

### Update connectors

- Make tokenization available to connectors. We will likely rely on it for section split decision for some document types.

In connectors we'll have connection specific code whose goal will be to create the `DocumentContentType`:

- Notion: repeat titles general metadata in `document.prefix` and repeat parent titles in `section.prefix` + something to show that content was ommitted
- Github: Issue / PR dicussion metadata in `document.prefix` no change otherwise. For code once we get there, some amount of logic around opening / closing {} maybe as a starter. We can rapidly iterate on that in `connectors`
- Drive: Need to investigate how docs are dumped. For slides probably something as well that depends on the format
- Slack: add document.prefix with thread metadata + not much change otherwise

**Comment by philipperolet** [comment]
>
```
  sections: {
    prefix:  string;
    content: string;
  };
```

This would be an array here correct?

**Comment by spolu** [comment]
> > 
> 
> ```
>   sections: {
>     prefix:  string;
>     content: string;
>   };
> ```
> 
> This would be an array here correct?

Yes def! Fixed :+1:

**Comment by philipperolet** [comment]
Thanks a lot :pray: This will def improve, repeating by section is a great idea. Before joining I had asked myself ~similar questions for email and ended up repeating title / chunk number / date etc. (but no section logic though). Happy to move forward with this. A few remarks:

1. WDYT about capping total metadata size to e.g. ~1/3 of chunk size?
2. Increasing chunk size from 256 => agree we should bump, but probably not too much, 512 or 1024 
   - AFAIU bigger chunks will have less precision / more recall (they contain more "concepts" so may match wider), so there is a sweet spot for the RAG to be careful with
   - the guideline of 256 tokens is indeed a bit old, but I thought it was based on the embedder also, not model context size? less knowledgeable than you on this though so I don't really know precisely why people used 256 initially
3. Would be a good time, while doing this, to ensure that we can continue easily changing chunking in the future; I see multiple topics that are not for now but may come later
   - we might want to test chunking strats such as overlap
   - we might want to change embedding size again
   - from previous XP, e.g. removing http links (consume lots of token, noisify the semantization) may turn a few percent of answers from wrong to right), etc.

**Comment by lasryaric** [comment]
Definitely onboard.

> for each section, balanced chunking strategy with a best-effort to split on newlines.

👍 I actually often think about it and wonder how many bad answers from the bot are just due to that issue.
Would be nice to have a way to diagnostic (at least just for us) exactly what was sent to the model for generation, that way we can gain intuition as a company on what works / what does not. WDYT?

**Comment by fontanierh** [comment]
Onboard as well, super bullish on repeating doc/sections context inside every chunk !

> the guideline of 256 tokens is indeed a bit old, but I thought it was based on the embedder also, not model context size? less knowledgeable than you on this though so I don't really know precisely why people used 256 initially

Embedding models have been able to embed a lot more than 256 tokens for a long time afaik, but if I understand correctly, having LLMs with larger context windows means you can grab bigger chunks while still giving the model the same # of chunks.

**Comment by spolu** [comment]
> Embedding models have been able to embed a lot more than 256 tokens for a long time afaik, but if I understand correctly, having LLMs with larger context windows means you can grab bigger chunks while still giving the model the same # of chunks.

Yes that's the motivation :+1:

**Comment by philipperolet** [comment]
> Embedding models have been able to embed a lot more than 256 tokens for a long time afaik, 

I am aware, and I had actually tried working with 2048-token embeddings in the past (with little success). My understanding was that people stayed with 256 for "quality" reasons,  related to the point I had written above,  "AFAIU bigger chunks will have less precision / more recall (they contain more "concepts" so may match wider), so there is a sweet spot for the RAG to be careful with"

Extreme example: if you could get to 900k-token embeddings, you could have a single embedding for the Bible; query-matching that would likely be poor because there's too much stuff being said in the bible. There's a good ratio to be found

> but if I understand correctly, having LLMs with larger context windows means you can grab bigger chunks while still giving the model the same # of chunks.

Why do we want to grab bigger chunks while keeping the # of chunks constant?
- if it is because we think bigger chunks work better, cf point above: probably, but not always and we don't want to go too far. (there are other ways to use the added context size)
- if it's for a technical reason i'm not aware of (or a non-technical one I missed) => this i'll be really glad to learn about :slightly_smiling_face: 

Really interesting topic! I had actually examples of bigger chunks performing worse than smaller ones for RAG when working on my email app, glad to talk about this more :student: 

As originally mentioned, having this discussion is long term (but valuable IMHO) and does not prevent moving forward with the plan above :+1:

**Comment by spolu** [comment]
The motivation for increasing from max 256 to max 512 (acknowledging that sectioning + balanced chunking will often result in less than 512 I think), is simply because we have more context of course and second because 256 definitely looks tight when you actually look at chunks, as a human.

**Comment by spolu** [comment]
Tasks created in [Caloris]
