### ISSUE TITLE
[Meru][New Pricing] Scrub workspace data when downgrade from the Pro plan.

### ISSUE THREAD

**Issue by lasryaric** [dust-tt/dust#4364]

**Comment by lasryaric** [comment]
>That’s an agressive departure from the existing right? As per other issue would love to get the final picture 🙏

Initial plan was to delete connected data sources, archive connected assistants, and remove static data sources.
The problem is that we need to tell the user exactly what is going to happen, and we think this is a weird message to share:
"We are deleting some of your data but keeping some other".  Given the nature of the data, we assumed it was better to remove everything to have the user feel safe and avoid getting customer support requests for scrubbing data.

**Comment by spolu** [comment]
Some late sleepless night thinking from last night. Just sharing in case useful:

Do we want to delete on downgrade or do we want to create some tooling in poke where we show all cancelled subscriptions accounts and move them through a simple pipeline where we attempt to contact them manually or automatically with a button push. And then we manually fully kill them with a button push and delete all their data sources.

Creating tooling in poke to support that workflow would reduce greatly the cost of handling the final deletion (1 simple button push) and would give us an opportunity to reach manually or semi-automatically (button push) to some of these accounts before we delete that data.

Also question: the main FUD we had before on automated deletion is that we had some account that unsubscribed because of failed payments and wanted to make sure we don't delete data in that case. What changed there? do we still rely on a manual process for failed payments? If so should we build some tooling in poke for that? If so should we build some tooling in poke for cancelled accounts since there's always a chance to get them back on?

A bit unstructured but hopefully you get my point. cc @Yutcam who is directly concerned by this process + cc @clmrn on chances of getting a cancelled account reactivated (from free trial).

**Comment by lasryaric** [comment]
@spolu I should have mentioned that this task is a commitment to take care of scrubbing the data but this is not planned before the release of the free trial. So we still have time to think through it.

I agree that after sleeping on it, I am less convinced this is the best solution.

**Comment by spolu** [comment]
Cool let's use that issue to discuss what we want there. 

I feel like a screen "cancelled accounts" in poke that lets you reach out to the account or fully terminate all its data could be an interesting solution here. It does require a bit of framing.

Curious to hear @gabhubert @Yutcam @clmrn take on that :+1:

**Comment by gabhubert** [comment]
I think we need to distinguish between (1) voluntary and (2) potentially involuntary trial interruption/downgrade

case (1) is what triggered this issue: if a user cancels their trial, what we want to avoid is that they then sign back up and find we've kept their data. In this case, data deletion should be prompt, and I think that reaching out is weird/deseperate. They've clicked the button to leave the party, you don't try to hold the Uber door to have them stay more :)

case (2) on failed payments is interesting. I think we should actually look into this more because it ties to the topic of retention/churn on pro plan, or at least it'll be hard to distinguish the 2. My view here is that we don't want to cancel upon the first failed payment, but that we likely want to limit access
- quickly and quite firmly for accounts with ~1 member (the admin just needs to get their shit together)
- more smoothly if the account is "thingish or potentially thingish" which could be:
  - many members, card failed because poorly anticipated payment cap
  
For case (2) I like Poké: it forces us to look at failed payments in the eyes an understand if we're being scammed by gmail squatters or if our email reminders are too weak. For case (1) mvp, I don't know that anything else but "prompt deletion" is ok. We could _potentially_ say that we edit copy to say "your data will be scheduled for prompt deletion" and handle manually within 24 hours but it's clear we'll want to automate as some quick point in the future anyway...

**Comment by spolu** [comment]
Thanks. Aligned. Full state has been raised which was the goal.

Looks like we want to nuke quick if cancel was clicked and otherwise have a queue for failed payments.

Whatever we do we’ll have to touch that logic

I know we have a manual process for failed payments. Curious what is our current process for explicit cancels?

**Comment by Yutcam** [comment]
Aligned with @gabhubert proposal. 

It's also important to help our users be more autonomous and improve the self-serve experience here: ie. as a user, from my account, I can request to delete my account and all my data. 

> I know we have a manual process for failed payments. Curious what is our current process for explicit cancels?

For explicit cancels = a user asks us to delete their data by email. 
We ask them to confirm they want all their connections, folders, and assistants deleted. Once they agree, we delete the following: 
- all the assistants one by one manually in poke
- all the data sources 
- we downgrade to a free test plan
- then select delete the workspace data (GDPR) 

//It takes some time, poke is slow, and the process involves multiple clicks. 

- Once done, we papertrail the deletion in #user-operations in Slack.

**Comment by Yutcam** [comment]
The way Livestorm does it is pretty good 

<img width="1827" alt="image" src="https://github.com/dust-tt/dust/assets/33726902/98ec5331-f592-46c0-9ce7-8049723702f4">

**Comment by PopDaph** [comment]
Output of IRL discussion with @spolu @lasryaric: 

Once a Stripe subscription is ended:
- We end the subscription on our backend so that the service is not accessible anymore. Admins of the workspace are redirected to the Paywall page, builder/users are redirected to the Paywall page with an adapted wording.
- We send an email to the workspace admins to let them know workspace is downgraded and that their data has been scheduled for removal in 15 days.
- We schedule a Temporal workflow in 12 days to send a reminder email: "Your data will be removed in 3 days" 
- We schedule a Temporal workflow in 15 days to delete the data.

If the user reactivates their subscription in between: 
- We cancel the scheduled workflows. 

After 12 days, on the scheduled workflow reminder email: 
- If there's a new subscription we do nothing, otherwise we email all admins to let them know data will be removed in 3 days.

After 15 days, on the scheduled workflow: 
- If there's a new subscription we do nothing, otherwise we delete most data to keep the workspace but empty.
    - We keep the workspace object and a Membership for the oldest admin user on this workspace.
    - All other membership are deleted (we need so see what it means for a user after login to have no membership). Or should we remove all user objects too? 
    - All the workspace data is deleted and no recovery is possible: all conversations, agents, datasources, dust apps, ....
- We send a confirmation email to the user.

**Comment by spolu** [comment]
Thanks @PopDaph :pray: 

Plan is also to create a poke page that shows workspaces that are
- late payment
- cancelled yet not scrubbed

To allow ops/sales to attempt reactivation at will.

As for membership, I would keep them :+1: But no strong feelings.

**Comment by lasryaric** [comment]
Thanks @PopDaph .

> Plan is also to create a poke page that shows workspaces that are

A metabase dashboard should work well and be less work no? We can link to it from Poke.

## Technical details

I think this should all happen in one workflow (your message seems to involve multiple workflows, I am not sure, so to be clear about what I had in mind):


```typescript


//front/scrub_workflow.ts

// This is triggered when the subscription is cancelled
async function ScrubWorkflow(workspaceId:string) {
  sendEmail('data will be deleted in 15 days')
  Workflow.sleep(12 days)
  if (shouldWeStillDelete() === false) {
   return ;
  }
  sendEmail('data will be deleted in 3 days')
  Workflow.sleep(3 days)
  if (shouldWeStillDelete() === false) {
    return ;
  }
  deleteEverything()
  sendEmail('All data deleted')
}
```

**Comment by PopDaph** [comment]
Thanks @spolu I forgot this part! 
- Late payments we can have easily with a Stripe link or MB dashboard. 
- Cancelled yet not scrubbed could be a MB dashboard.

-> Cool think about having them on MB is that 1/ cheap and 2/ can be added to [Customers and Pilots MB dashboard](https://metabase.dust.tt/dashboard/7-subscriptions-monitoring?tab=1-active-and-valid-subscriptions)


👍🏻 to keep Memberships especially if it means that we don't automatically create a empty workspace for those orphaned users.

**Comment by PopDaph** [comment]
Nice @lasryaric indeed it's best to do it with a single workflow, thanks for sharing 👍🏻
