### ISSUE TITLE
Dust apps datasource block should use Dust's keys

### ISSUE THREAD

**Issue by albandum** [dust-tt/dust#5294]
Currently the datasource block is using the customer's OpenAI key leading to issues like so: 

![image (1)](https://github.com/dust-tt/dust/assets/1189312/6d65831a-c19a-456e-a353-37d23d132a37)

We decided to switch that to our own keys to ensure a smooth experience on the user side.

Made this an eng runner card because Pennylane is stuck because of this.
Full context here: https://dust4ai.slack.com/archives/C068M21DQFP/p1716820057109629

**Comment by spolu** [comment]
For data sources interactions I think we want to take ownership of the credentials since data sources have been thought lately as a separate packaged product outside of Dust apps. Also you can't "pick" your embedding models in Dust apps because this is managed by us so if you don't have a valid OpenAI API key then you can't use it in Dust apps.

This is to some extent related to the provider deactivation project (cc @JulesBelveze)

Proposal:

We move `core` data source embedding to run on our own keys, that means we expose as an env variable `CORE_DATA_SOURCES_OPENAI_API_KEY` and `CORE_DATA_SOURCES_MISTRAL_API_KEY` 

In the future if someone really really wants to embed on azure or their own credentials we will be able to add a field to the to the new `Embedder` config: something like `use_own_credentials`. In which case we would not look for `CORE_DATA_SOURCES_...` credentials but instead the ones passed by front. In front we would have to be able to inject them properly based on the workspace configuration of course. But I think from `core` perspective that looks flexible enough cc @flvndvd 

Immediate proposal is to move all data sources interactions to internal core credentials on our own managed keys.

- [ ] add core secrets `CORE_DATA_SOURCES_OPENAI_API_KEY` and `CORE_DATA_SOURCES_MISTRAL_API_KEY`
- [ ] in OpenAI and Mistral Embedder implementations (the one currently supported for data sources) give priority to env variable `CORE_DATA_SOURCES_OPENAI_API_KEY` and `CORE_DATA_SOURCES_MISTRAL_API_KEY`. Note: that means we would go to the env at each call which is not great so we likely want to introduce a bit of tooling in core for that.

Financial impact should be ~0 (volume of embedding coming from using data sources in dust-apps. Likely ~$0).

**Comment by spolu** [comment]
@JulesBelveze happy to pair on it with you. Nice eng runner Rust task :)

**Comment by JulesBelveze** [comment]
@spolu Checking that I'm getting everything right:
- When you mean `data_source` here, you mean  a `data_source` block, right?
- How are k8s secrets generated?

**Comment by spolu** [comment]
Yes the data_source block but really the `src/data_source/data_source.rs` file :+1:

**Comment by spolu** [comment]
> How are k8s secrets generated?

```
kubectl patch secret core-secrets -p '{"stringData":{"'QDRANT_CLUSTER_0_URL'":"https://baeae841-6259-4484-b632-cf33c9bbb537.us-east4-0.gcp.cloud.qdrant.io"}}'
```

Then it's available in the env

**Comment by JulesBelveze** [comment]
Oh okay they are manually created, was looking for a yaml 😅

**Comment by JulesBelveze** [comment]
Done in #5308

**Comment by albandum** [comment]
Awesome thanks - will ping customer !
