### ISSUE TITLE
Notion Workflow missing GC workflow

### ISSUE THREAD

**Issue by lasryaric** [dust-tt/dust#5513]
This Notion workflow is missing its garbage collect workflow, and we don't understand why.
As per IRL, @fontanierh it's yours to investigate.
Thanks!

https://cloud.temporal.io/namespaces/dust-prod.gmnlm/workflows?query=WorkflowId+BETWEEN+%27workflow-notion-14bba9443a%27+AND+%27workflow-notion-14bba9443a%7E%27

**Comment by lasryaric** [comment]
@fontanierh I had to restart quite a few today, something like 5 or 6.
I had to restart 3 of them for this alert:
https://dust4ai.slack.com/archives/C05F84CFP0E/p1718036100401609

**Comment by fontanierh** [comment]
Thanks ! 5 or 6 is definitely not normal, will take a look

**Comment by philipperolet** [comment]
👋 
Since we get a few monitors regarding this, this is IMHO eng runner, not olympus, moving it in eng runner board
@fontanierh I've started having a look too and will submit a PR, I can reassign to me if it helps? 

from what I observed, it's transient and I bet it's because some workflows get continued_as_new'd before the status === RUNNING check happens

**Comment by fontanierh** [comment]
Thanks 🙏  I did not have time to look into it at all yet

**Comment by philipperolet** [comment]
Fixed by https://github.com/dust-tt/dust/pull/5623
