### ISSUE TITLE
[MS connector] Garbage collection

### ISSUE THREAD

**Issue by tdraier** [dust-tt/dust#5751]
Implement garbage collection : remove indexed resources that do not exist anymore

**Comment by philipperolet** [comment]
codependency with #6290

**Comment by philipperolet** [comment]
Theoretically, garbage collection is not needed since deletions are picked up in incremental syncs
In practice, a sanity check that each node is still live would give us a stronger guarantee:
- perpetually running workflow microsoft-{connId}-garbageCollector
- check all nodes in our connectors' table are still live
- spread the check at 1qps and max once per day, to avoid oversollicitation of ms api
With this rate a 200,000 item drive would be fully garbage collected in less than 2 days
- optional: limit the check to items unseen for more than a week

Add the garbage collect workflow to monitoring

**Comment by philipperolet** [comment]
Note: while garbage collection **flow** is not theoretically required, deletion code is, and should be written when folders are deselected from add/remove resources
