### ISSUE TITLE
Map section should show its output in a visually different way

### ISSUE THREAD

**Issue by aickin** [dust-tt/dust#60]
When you run a `map` block over an array that is output from a previous block, the UI shows the output of the `map` block identically to the previous block (see picture below). When I saw this, I got confused, because it didn't seem like the `map` block was fanning out jobs across the array. But when I put a `search` block between map and reduce, it was clear that search ran once for each element of the array. Further, the output from `search` is different than the output from `map`, with a green check next to each individual run of the block.

I think I would want the output of the `map` block to look more like the output of the blocks inside of map-reduce. Other ideas are to have `map` output a flat list of all of its results with small visual indicators in between the different clusters that will reduce down together.

Note in the picture here that the output of INPUT and LOOP are the same. I think that LOOP's output should look more like SEARCH to indicate that there will be 3 runs, not one run on an array of 3:

![dust tt_aickin_a_989e0ff2d5](https://user-images.githubusercontent.com/44199/199073922-4b9e8c6d-754c-401b-87ca-a881b267307b.png)

**Comment by spolu** [comment]
Agreed! An immediate fix would be to hide the outputs of the `map` block as they are hidden for the `reduce` block?

**Comment by spolu** [comment]
I think the right solution here is to hide the outputs unless there are errors. Will work towards that.

**Comment by spolu** [comment]
Actually it would be better indeed for the map block to output mapped stuff directly. I wonder why I decided against that, need to re-investigate the execution engine code. Wilco.

**Comment by spolu** [comment]
Okay now I remember why. The idea is that the map block execution checks that the from/repeat parameter are valid and guarantees to output an array on which we can split the execution stream.

That's why the "split" is done after the map block is executed.

Will think of ways to improve the situation

**Comment by spolu** [comment]
Ok now I have recovered the whole thinking.

Errors in the map block happen before the "logic map operation" but outputs should be displayed after the "logic map operation".

I favored the output of errors non repeated. We can handle this in the UI. show as is when errors are present, fix it on the fly otherwise.
