### ISSUE TITLE
Consider renaming map-reduce blocks some kind of "loop" in the UI

### ISSUE THREAD

**Issue by aickin** [dust-tt/dust#62]
Personally, I found the names `map` and `reduce` a little misleading; it made it seem like they were part of a massive parallel processing engine, and it also made it seem like the reduce step should have logic. Having read over the code, I'm pretty sure they are more similar to a for loop.

In light of this, maybe we should rename `map` and `reduce` blocks in the UI to one of the following:

* `loop` and `end_loop`
* `for_each` and `end_for_each`
* `each` and `end_each`

**Comment by spolu** [comment]
We'll have to add a `while/end_while` block soon. Maybe we could call this one `each/end_for_each` but this is more a `map` than a `for_each`. So maybe what you're asking for is a `end_map` instead of `reduce`?

That all being said, this will require cutting a new version of the specification language because it's not backward compatible. Which won't happen right now I think.

We could obviously just update the UI, but I'm not in favor of that as I want to keep the UI and the underlying specification language apps compile to, closely related to avoid taking debt in that direction.

**Comment by spolu** [comment]
Will not change the name just now and revisit in the future.
