### ISSUE TITLE
Headless CMS for site

### ISSUE THREAD

**Issue by albandum** [dust-tt/dust#6503]

**Comment by spolu** [comment]
As per earlier discussions I think we can continue longer without a CMS.

How many times did we edited or attempted the website in the last 3 months? I think not that very often.

We want to be conservative on introducing new systems as much as possible. Try to push until it's too painful to continue otherwise.

**Comment by albandum** [comment]
Well we didn't change the website because it's currently not possible - we need to add something like 40 use cases on the site somewhere and it doesn't seem like good eng time to have to do it, no ? 🤔

**Comment by spolu** [comment]
We will need a fair amount of eng time to integrate strapi make sure the design works consistently and expand well with strapi updates.

We can get 80% of the value of strapi by having a committed JSON in the code for repetitive elements such as templates right. without having to support a new system.

**Comment by albandum** [comment]
Ok, yeah JSON can do the trick indeed.
(we're not considering webflow right ? 🤓 )
