### ISSUE TITLE
Add an option to version prompts on GitHub

### ISSUE THREAD

**Issue by renatocaliari** [dust-tt/dust#657]
Currently, as far as I know, there is no way to version or backup blocks, especially LLM prompts. 
It would be great if we could have an option that allowed us to save these blocks (or at least the prompts) in our own GitHub repository.

Or am I missing some other existing way?

**Comment by renatocaliari** [comment]
any suggestions?

**Comment by spolu** [comment]
Hi @renatocaliari apps are versioned and you can somewhat easily find old versions by looking at execution logs of your app.

Intergration with github is not on the roadmap for us, the whole point is to store your prompts in Dust and iterate on it there so that you don't have to manage that complexity in your codebase.

**Comment by spolu** [comment]
Thanks for the suggestion though :pray:

**Comment by renatocaliari** [comment]
> Hi @renatocaliari apps are versioned and you can somewhat easily find old versions by looking at execution logs of your app.
> 
> Intergration with github is not on the roadmap for us, the whole point is to store your prompts in Dust and iterate on it there so that you don't have to manage that complexity in your codebase.

Got it! Thanks for the reply. :)

It would be great to have the prompts versioned on GitHub, so I can use them in different locations without the risk of being tied to a single platform. 
Nonetheless, I really appreciate having dust.tt for free to manage my prompts and handle the logging aspect.
