### ISSUE TITLE
Website deletion error

### ISSUE THREAD

**Issue by JulesBelveze** [dust-tt/dust#6634]
We currently get the following error when attempting to delete a website
```
API Error
    method: "DELETE"
    url: "/api/w/XTCqEpuFST/data_sources/docs.dust.tt"
    statusCode: 500
    apiError: {
      "status_code": 500,
      "api_error": {
        "type": "internal_server_error",
        "message": "Error deleting core data source: Failed to delete data source (error: status: Cancelled, message: \"Timeout expired\", details: [], metadata: MetadataMap { headers: {} }\n\nCaused by:\n    0: transport error\n    1: Timeout expired)",
        "data_source_error": {
          "code": "internal_server_error",
          "message": "Failed to delete data source (error: status: Cancelled, message: \"Timeout expired\", details: [], metadata: MetadataMap { headers: {} }\n\nCaused by:\n    0: transport error\n    1: Timeout expired)"
        }
      }
    }
```
which then leads to the following scenario:
- the website is properly delete in the connectors db
- the website is not deleted in the front db

**Comment by spolu** [comment]
If confirmed this is clearly not an olympus task but an eng runner task. Moving back to eng-runner.

**Comment by spolu** [comment]
(@JulesBelveze would have been useful to have references to logs in datadog 🙏)

**Comment by spolu** [comment]
Task description does not look correct since we have many good websites deletions happening daily: https://app.datadoghq.eu/logs?query=service%3Afront%20%40route%3A%2Fapi%2Fw%2F%2A%2Fdata_sources%2F%5C%5Bname%5C%5D%20%40method%3ADELETE&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice&event=AgAAAZFscqJMsv_X_QAAAAAAAAAYAAAAAEFaRnNjcV9wQUFCNjhWdkZ6Ykxac3dBUQAAACQAAAAAMDE5MTZjODQtMTNiZi00MzcyLThkM2UtZmIxMGE1NzgyYzg0&fromUser=true&messageDisplay=inline&refresh_mode=sliding&storage=hot&stream_sort=desc&viz=stream&from_ts=1723717019847&to_ts=1724321819847&live=true

**Comment by spolu** [comment]
We delete the connector then core then we data source. This seems like the right order. This has to be an isolated timeout.

**Comment by spolu** [comment]
Reopen if I miunderstood anything
