### ISSUE TITLE
[Groups Infra] Filter assistants based on user's vaults/permissions

### ISSUE THREAD

**Issue by flvndvd** [dust-tt/dust#6763]
Update the listing of assistants to filter on user's vaults. This requires:
- Add `acl` on the `agent_configurations` table that is a union of the vaults used by data source's actions  
- List `agent_configurations` based on acls.

Follow up items: https://github.com/dust-tt/dust/issues/6903

**Comment by philipperolet** [comment]
Hey :)
Had a look at the tasks. I will do the following:
- change the `DataSourceViewType` so instead of a vaultId, it gets a `VaultType`
- change the `DataSourceConfigurationType` so instead of a datasourceviewid it gets a `DataSourceViewType`
- in `getAgentConfigurations`, grab the user's groups and filter the agent list accordingly given the info above
No need to add an acl to the agent_config table AFAICT
Happy to discuss if needed 👍

**Comment by flvndvd** [comment]
IIRC, the listing occurs in the light version of the assistant configurations, which doesn't retrieve all the associated actions. If that's true, we should still denormalize because the proposed plan will only be effective with the complete version, right?

The plan does not capture query tables as well.

**Comment by philipperolet** [comment]
As per IRL, will denormalize. Following current naming schemes, will add a `groupsId INTEGER[]`

**Comment by philipperolet** [comment]
**Decision on using a new array column VS a joined table `AgentConfigurationGroup` => decided on Array column**
- Advantage is that it's a real denormalization, avoid another fetch in the call to list agents that's already harsh + generally simpler
- Drawback is we don't get the checks on FK constraint => not a real drawback since we already have these checks on the actions (and chainedly so up to the agent configs)
- Drawback 2 is the reverse query (list agents by group) is more complex => ignored because we don't have an incentive to make that query simple at the time (we don't make that query or have direct plans to make it)

Lastly, a joined table would kind of imply we can add agents to groups, so the source of truth is not only the actions but something new that changes the product. It's always simple to migrate to a joined table if needed later on --- simpler in that direction than the reverse
