### ISSUE TITLE
[Dust Apps] add support for passing the current vault in Dust Apps Components

### ISSUE THREAD

**Issue by spolu** [dust-tt/dust#7153]

**Comment by spolu** [comment]
Start with passing the global vault

**Comment by PopDaph** [comment]
Taking!

**Comment by PopDaph** [comment]
Quick framing to make sure we're aligned on the new routes and the todo. 

Since both route must work I'll have to duplicate some code, I'll duplicate only the getServerSideProps and not the page components.
I'll keep the full screen modal, no design change at all with the current pages accessible from vaults (with the old urls). 

##  URLs from /build that must keep working. 

List of apps from Build: 
- /w/[wId]/a

App pages: 
- Specs: /w/[wId]/a/[aId]
- Datasets: /w/[wId]/a/[aId]/datasets
- Logs:  /w/[wId]/a/[aId]/runs
- Settings: /w/[wId]/a/[aId]/settings

## Urls from the new Data Sources menu

List of apps in vault: 
- /w/[wId]/data-sources/vaults/[vId]/categories/apps

App pages: 
- Specs: /w/[wId]/data-sources/vaults/[vId]/categories/apps/[aId]
- Datasets: /w/[wId]/data-sources/vaults/[vId]/categories/apps/[aId]/datasets
- Logs:  /w/[wId]/data-sources/vaults/[vId]/categories/apps/[aId]/runs
- Settings: /w/[wId]/data-sources/vaults/[vId]/categories/apps/[aId]/settings

**Comment by fontanierh** [comment]
LGTM

BTW but for the vault ones, we are removing the `/data-sources` from the URL (menu name won't be data source anymore see https://github.com/dust-tt/dust/issues/7196)

**Comment by PopDaph** [comment]
@fontanierh Thanks for linking! 🙏🏻  This should be transparent since my pages will be under /vaults

**Comment by PopDaph** [comment]
Ok to many cooks in the kitchen, stepping down of this one cf IRL discussion with @fontanierh

**Comment by PopDaph** [comment]
Closing, discussed IRL cc @fontanierh @tdraier 
Covered by https://github.com/dust-tt/dust/issues/7154 & https://github.com/dust-tt/dust/issues/7149
