### ISSUE TITLE
[Remote Databases] [Step 1] Snowflake connector skeleton + displayed as Early access

### ISSUE THREAD

**Issue by fontanierh** [dust-tt/dust#7451]
[data model](https://www.notion.so/dust-tt/Design-Doc-Remote-Databases-e28217bc290b465a9e892ab4c20b0da6?pvs=4#7dc9bbcd1f104fc3ba70f979c7fec108)

[design doc](https://www.notion.so/dust-tt/Design-Doc-Remote-Databases-e28217bc290b465a9e892ab4c20b0da6?pvs=4#4cfdc41873e947fb8680f4c9834ad3a4)

Much of the logic should be shared across remote database connectors. We're starting with Snowflake, since it is the one we have.

This task includes fetching secrets from `oauth`, connecting to a Snowflake DB from `connectors`, retrieving list of schemas / tables from snowflake, saving the tables in `core` and implementing the `content-nodes` API. Can potentially be broken down in smaller task if needed.

**Comment by PopDaph** [comment]
# Discussed

cc @fontanierh 

### Setting permissions.

When the admin initiates the connection, we list in a tree the db > schemas > tables. 
The admin can select at the table level. 

Once submitted, we save on db the list of db/schemas/tables selected with read permissions.

### Keeping data fresh

A cron workflow running every 4 hours makes sure to refresh the tables available from the set permissions.
 
Eventually, on the UI of the connector, we will add a refresh button to allow refreshing the list of tables. 

We do not store the structure of each table, this is done at query time on Core. 
Why? We think it's crucial for this connector to get ultra fresh data, even if it means the action is slower. Also, it is less complexity for us since it means we don't need to keep this sync. 


### Excluding data?

Do we want to keep tables such as information_schema. A priori no?

**Comment by PopDaph** [comment]
Added my comments to the Design doc
https://dust4ai.slack.com/archives/C05BUSJQP5W/p1727256715313099
