### ISSUE TITLE
[Ext] Consistent content fragment preview/download [[[NOT MVP]]]

### ISSUE THREAD

**Issue by tdraier** [dust-tt/dust#8626]
Right now citations cannot be clicked or previewed like in front app. 

This has been disabled for now for multiple reasons : 
- download url is stored in database as a private api url. 
- using a public api (/v1) is not a solution, as `<img>` tags does not support token authorization.

We should either : 
- keep it as it is, and tell that we need to go the app to see the fragment
- or send a session cookie that will be usable with the private api

**Comment by tdraier** [comment]
Currently the link is restored, using : 
- the original source url for tab content
- or the private file link, which works noly if you are logged in to the app (outside extension)

**Comment by PopDaph** [comment]
# After IRL discussion - What we want: 

There’s a different behavior when I just uploaded a content fragment and then when it’s posted on a message. We want to harmonize + always allow to download the content of the fragment to inspect what was extracted.

We're okay to not have the background image in the citation since it's complex to handle

**Comment by PopDaph** [comment]
Closing, referenced on the feedback doc: https://www.notion.so/dust-tt/Centralized-Feedback-about-Chrome-extension-15028599d941801b87e8dd93a8bad8be
